# Generated by Django 5.1.7 on 2025-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smoke_level', models.IntegerField()),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
